<a href="https://colab.research.google.com/github/Rohan171819/Deep_Learning./blob/main/Back_Propagation_Classification_Mathematical_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [134]:
import pandas as pd
import numpy as np

In [135]:
Data=pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]],columns=["iq","resume_score","placement"])
Data

iq  resume_score  placement
0   8             8          1
1   7             9          1
2   6            10          0
3   5             5          0

In [136]:
def initialize_parameters(layer_dims):
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)
  for l in range(1, L):
    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
  return parameters

In [137]:
# Utility Function...
def sigmoid(Z):
  a=1/1+np.exp(-Z)
  return a

In [138]:
def linear_forward(A_prev, W, b):
  Z = np.dot(W.T, A_prev) + b
  b = sigmoid(Z)
  return b

In [139]:
# Forward Propagation...
def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network

  for l in range(1, L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    print("A"+str(l-1)+": ", A_prev)
    print("W"+str(l)+": ", Wl)
    print("b"+str(l)+": ", bl)
    print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    print("A"+str(l)+": ", A)
    print("**"*20)

  return A,A_prev

In [140]:
#
X=Data[["iq","resume_score"]].values[0].reshape(2,1)
y=Data[["placement"]].values[0][0]

# Parameters Initialization...
parameters=initialize_parameters([2,3,1])
y_hat,A1=L_layer_forward(X,parameters)
y_hat=y_hat[0][0]
print("Y_hat value is",y_hat)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]
b1:  [[0.]
 [0.]
 [0.]]
----------------------------------------
A1:  [[1.20189652]
 [1.20189652]
 [1.20189652]]
****************************************
A1:  [[1.20189652]
 [1.20189652]
 [1.20189652]]
W2:  [[0.1]
 [0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[1.69727949]]
****************************************
Y_hat value is 1.6972794922600538


In [141]:
A1

array([[1.20189652],
       [1.20189652],
       [1.20189652]])

In [142]:
update_parameters(parameters,y,y_hat,A1,X)

In [143]:
parameters

{'W1': array([[0.10001352, 0.10001352, 0.10001352],
        [0.10001352, 0.10001352, 0.10001352]]),
 'b1': array([[1.00015215e-01],
        [1.69059150e-06],
        [1.69059150e-06]]),
 'W2': array([[0.09991619],
        [0.09991619],
        [0.09991619]]),
 'b2': array([[-6.97279492e-05]])}

In [144]:
def update_parameters(parameters,y,Y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001*(y-Y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001*(y-Y_hat)*A1[1][0])
  parameters['W2'][2][0] = parameters['W2'][2][0] + (0.0001*(y-Y_hat)*A1[2][0])
  parameters['b2'][0][0] = parameters['b2'][0][0] + (0.0001*(y-Y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001*(y-Y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0]) #iq
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001*(y-Y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0]) #iq
  parameters['W1'][0][2] = parameters['W1'][0][2] + (0.0001*(y-Y_hat)*parameters['W2'][2][0]*A1[2][0]*(1-A1[2][0])*X[0][0]) #iq
  parameters['b1'][0][0] = parameters['W1'][0][1] + (0.0001*(y-Y_hat)*parameters['W2'][0][0]*A1[1][0]*(1-A1[1][0])) #iq

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001*(y-Y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0]) #cgpa
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001*(y-Y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0]) #cgpa
  parameters['W1'][1][2] = parameters['W1'][1][2] + (0.0001*(y-Y_hat)*parameters['W2'][2][0]*A1[2][0]*(1-A1[2][0])*X[1][0]) #cgpa
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001*(y-Y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])) #cgpa
  parameters['b1'][2][0] = parameters['b1'][2][0] + (0.0001*(y-Y_hat)*parameters['W2'][2][0]*A1[2][0]*(1-A1[2][0])) #cgpa

In [145]:
X=Data[["iq","resume_score"]].values[1].reshape(2,1)
y=Data[["placement"]].values[1][0]
y_hat,A1=L_layer_forward(X,parameters)
y_hat=y_hat[0][0]
print("Y_hat value is",y_hat)

A0:  [[7]
 [9]]
W1:  [[0.10001352 0.10001352 0.10001352]
 [0.10001352 0.10001352 0.10001352]]
b1:  [[1.00015215e-01]
 [1.69059150e-06]
 [1.69059150e-06]]
----------------------------------------
A1:  [[1.18264122]
 [1.20185249]
 [1.20185249]]
****************************************
A1:  [[1.18264122]
 [1.20185249]
 [1.20185249]]
W2:  [[0.09991619]
 [0.09991619]
 [0.09991619]]
b2:  [[-6.97279492e-05]]
----------------------------------------
A2:  [[1.69888831]]
****************************************
Y_hat value is 1.6988883094979297


In [146]:
A1

array([[1.18264122],
       [1.20185249],
       [1.20185249]])

In [147]:
update_parameters(parameters,y,y_hat,A1,X)

In [148]:
parameters

{'W1': array([[0.10002407, 0.10002537, 0.10002537],
        [0.10002709, 0.10002876, 0.10002876]]),
 'b1': array([[1.00027066e-01],
        [3.38322797e-06],
        [3.38322797e-06]]),
 'W2': array([[0.09983354],
        [0.0998322 ],
        [0.0998322 ]]),
 'b2': array([[-0.00013962]])}

In [149]:
X=Data[["iq","resume_score"]].values[2].reshape(2,1)
y=Data[["placement"]].values[2][0]
y_hat,A1=L_layer_forward(X,parameters)
y_hat=y_hat[0][0]
print("Y_hat value is",y_hat)

A0:  [[ 6]
 [10]]
W1:  [[0.10002407 0.10002537 0.10002537]
 [0.10002709 0.10002876 0.10002876]]
b1:  [[1.00027066e-01]
 [3.38322797e-06]
 [3.38322797e-06]]
----------------------------------------
A1:  [[1.18260272]
 [1.20180706]
 [1.20180706]]
****************************************
A1:  [[1.18260272]
 [1.20180706]
 [1.20180706]]
W2:  [[0.09983354]
 [0.0998322 ]
 [0.0998322 ]]
b2:  [[-0.00013962]]
----------------------------------------
A2:  [[1.69915565]]
****************************************
Y_hat value is 1.6991556538591834


In [150]:
update_parameters(parameters,y,y_hat,A1,X)

In [151]:
parameters

{'W1': array([[0.10004601, 0.10005001, 0.10005001],
        [0.10006365, 0.10006982, 0.10006982]]),
 'b1': array([[1.00054113e-01],
        [7.48891310e-06],
        [7.48891310e-06]]),
 'W2': array([[0.0996326 ],
        [0.09962799],
        [0.09962799]]),
 'b2': array([[-0.00030953]])}

In [152]:
X=Data[["iq","resume_score"]].values[3].reshape(2,1)
y=Data[["placement"]].values[3][0]
y_hat,A1=L_layer_forward(X,parameters)
y_hat=y_hat[0][0]
print("Y_hat value is",y_hat)

A0:  [[5]
 [5]]
W1:  [[0.10004601 0.10005001 0.10005001]
 [0.10006365 0.10006982 0.10006982]]
b1:  [[1.00054113e-01]
 [7.48891310e-06]
 [7.48891310e-06]]
----------------------------------------
A1:  [[1.33267063]
 [1.36765635]
 [1.36765635]]
****************************************
A1:  [[1.33267063]
 [1.36765635]
 [1.36765635]]
W2:  [[0.0996326 ]
 [0.09962799]
 [0.09962799]]
b2:  [[-0.00030953]]
----------------------------------------
A2:  [[1.66698907]]
****************************************
Y_hat value is 1.6669890712596338


In [153]:
A1

array([[1.33267063],
       [1.36765635],
       [1.36765635]])

In [154]:
update_parameters(parameters,y,y_hat,A1,X)

In [155]:
parameters

{'W1': array([[0.10008274, 0.10009167, 0.10009167],
        [0.10010038, 0.10011147, 0.10011147]]),
 'b1': array([[1.00099999e-01],
        [1.58207013e-05],
        [1.58207013e-05]]),
 'W2': array([[0.09941044],
        [0.09940001],
        [0.09940001]]),
 'b2': array([[-0.00047623]])}

In [158]:
# epochs implementation
parameters = initialize_parameters([2,3,1])
epochs = 10
for i in range(epochs):
  for j in range(Data.shape[0]):

    X = Data[['iq', 'resume_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = Data[['placement']].values[j][0]

    # Parameter initialization
    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)
parameters

A0:  [[8]
 [8]]
W1:  [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]
b1:  [[0.]
 [0.]
 [0.]]
----------------------------------------
A1:  [[1.20189652]
 [1.20189652]
 [1.20189652]]
****************************************
A1:  [[1.20189652]
 [1.20189652]
 [1.20189652]]
W2:  [[0.1]
 [0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[1.69727949]]
****************************************
A0:  [[7]
 [9]]
W1:  [[0.10001352 0.10001352 0.10001352]
 [0.10001352 0.10001352 0.10001352]]
b1:  [[1.00015215e-01]
 [1.69059150e-06]
 [1.69059150e-06]]
----------------------------------------
A1:  [[1.18264122]
 [1.20185249]
 [1.20185249]]
****************************************
A1:  [[1.18264122]
 [1.20185249]
 [1.20185249]]
W2:  [[0.09991619]
 [0.09991619]
 [0.09991619]]
b2:  [[-6.97279492e-05]]
----------------------------------------
A2:  [[1.69888831]]
****************************************
A0:  [[ 6]
 [10]]
W1:  [[0.10002407 0.10002537 0.10002537]
 [0.10002709 0.10002876 0.10002876]]
b1

{'W1': array([[0.10079291, 0.10089184, 0.10089184],
        [0.10096428, 0.10108408, 0.10108408]]),
 'b1': array([[0.10089973],
        [0.00015388],
        [0.00015388]]),
 'W2': array([[0.09407868],
        [0.09396248],
        [0.09396248]]),
 'b2': array([[-0.0047985]])}