<a href="https://colab.research.google.com/github/Rohan171819/Deep_Learning./blob/main/Back_Propagation_Regression_Mathematical_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
Data=pd.DataFrame([[8,8,3],[6,9,5],[7,5,8],[12,7,11]],columns=["iq","cgpa","lpa"])
Data

iq  cgpa  lpa
0   8     8    3
1   6     9    5
2   7     5    8
3  12     7   11

In [3]:
def initialize_parameters(layer_dims):
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)
  for l in range(1, L):
    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
  return parameters

In [4]:
initialize_parameters([2,3,1])

{'W1': array([[0.1, 0.1, 0.1],
        [0.1, 0.1, 0.1]]),
 'b1': array([[0.],
        [0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [5]:
def linear_forward(A_prev, W, b):
  Z = np.dot(W.T, A_prev) + b
  return Z

In [6]:
# Forward Propagation...
def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network

  for l in range(1, L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    print("A"+str(l-1)+": ", A_prev)
    print("W"+str(l)+": ", Wl)
    print("b"+str(l)+": ", bl)
    print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    print("A"+str(l)+": ", A)
    print("**"*20)

  return A,A_prev

In [7]:
X=Data[["iq","cgpa"]].values[0].reshape(2,1)
y=Data[["lpa"]].values[0][0]

# Parameters Initialization...
parameters=initialize_parameters([2,3,1])
Y_hat,A1=L_layer_forward(X,parameters)


A0:  [[8]
 [8]]
W1:  [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]
b1:  [[0.]
 [0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.48]]
****************************************


In [8]:
Y_hat=Y_hat[0][0]

In [9]:
Y_hat

0.4800000000000001

In [10]:
A1

array([[1.6],
       [1.6],
       [1.6]])

In [11]:
def update_parameters(parameters,y,Y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 *(y-Y_hat) * A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 *(y-Y_hat) * A1[1][0])
  parameters['W2'][2][0] = parameters['W2'][2][0] + (0.001 * 2 *(y-Y_hat) * A1[2][0])
  parameters['b2'][0][0] = parameters['b2'][0][0] + (0.001 * 2 *(y-Y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 *(y-Y_hat) * parameters['W2'][0][0] * X[0][0]) #iq
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 *(y-Y_hat) * parameters['W2'][1][0] * X[0][0]) #iq
  parameters['W1'][0][2] = parameters['W1'][0][2] + (0.001 * 2 *(y-Y_hat) * parameters['W2'][2][0] * X[0][0]) #iq
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 *(y-Y_hat) * parameters['W2'][0][0])           #iq

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 *(y-Y_hat) * parameters['W2'][0][0] * X[1][0]) #cgpa
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 *(y-Y_hat) * parameters['W2'][1][0] * X[1][0]) #cgpa
  parameters['W1'][1][2] = parameters['W1'][1][2] + (0.001 * 2 *(y-Y_hat) * parameters['W2'][2][0] * X[1][0]) #cgpa
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 *(y-Y_hat) * parameters['W2'][1][0]) #cgpa
  parameters['b1'][2][0] = parameters['b1'][2][0] + (0.001 * 2 *(y-Y_hat) * parameters['W2'][2][0]) #cgpa

In [12]:
update_parameters(parameters,y,Y_hat,A1,X)

In [13]:
parameters

{'W1': array([[0.10435714, 0.10435714, 0.10435714],
        [0.10435714, 0.10435714, 0.10435714]]),
 'b1': array([[0.00054464],
        [0.00054464],
        [0.00054464]]),
 'W2': array([[0.108064],
        [0.108064],
        [0.108064]]),
 'b2': array([[0.00504]])}

In [30]:
X=Data[["iq","cgpa"]].values[1].reshape(2,1)
y=Data[["lpa"]].values[1][0]
Y_hat,A1=L_layer_forward(X,parameters)

A0:  [[6]
 [9]]
W1:  [[ 0.85315217  0.85315217  0.85315217]
 [-0.09010916 -0.09010916 -0.09010916]]
b1:  [[0.06770414]
 [0.06770414]
 [0.06770414]]
----------------------------------------
A1:  [[4.37563478]
 [4.37563478]
 [4.37563478]]
****************************************
A1:  [[4.37563478]
 [4.37563478]
 [4.37563478]]
W2:  [[0.36747244]
 [0.36747244]
 [0.36747244]]
b2:  [[0.14211271]]
----------------------------------------
A2:  [[4.96588831]]
****************************************


In [31]:
Y_hat=Y_hat[0][0]

In [32]:
Y_hat

4.965888305122267

In [33]:
update_parameters(parameters,y,Y_hat,A1,X)

In [34]:
parameters

{'W1': array([[ 0.85330272,  0.85330272,  0.85330272],
        [-0.08988334, -0.08988334, -0.08988334]]),
 'b1': array([[0.06772923],
        [0.06772923],
        [0.06772923]]),
 'W2': array([[0.36777096],
        [0.36777096],
        [0.36777096]]),
 'b2': array([[0.14218094]])}

In [35]:
X=Data[["iq","cgpa"]].values[2].reshape(2,1)
y=Data[["lpa"]].values[2][0]
Y_hat,A1=L_layer_forward(X,parameters)

A0:  [[7]
 [5]]
W1:  [[ 0.85330272  0.85330272  0.85330272]
 [-0.08988334 -0.08988334 -0.08988334]]
b1:  [[0.06772923]
 [0.06772923]
 [0.06772923]]
----------------------------------------
A1:  [[5.59143155]
 [5.59143155]
 [5.59143155]]
****************************************
A1:  [[5.59143155]
 [5.59143155]
 [5.59143155]]
W2:  [[0.36777096]
 [0.36777096]
 [0.36777096]]
b2:  [[0.14218094]]
----------------------------------------
A2:  [[6.31127943]]
****************************************


In [36]:
Y_hat=Y_hat[0][0]

In [37]:
Y_hat

6.311279431507638

In [38]:
update_parameters(parameters,y,Y_hat,A1,X)

In [39]:
parameters

{'W1': array([[ 0.86244407,  0.86244407,  0.86244407],
        [-0.08335381, -0.08335381, -0.08335381]]),
 'b1': array([[0.06903514],
        [0.06903514],
        [0.06903514]]),
 'W2': array([[0.38665569],
        [0.38665569],
        [0.38665569]]),
 'b2': array([[0.14555838]])}

In [40]:
X=Data[["iq","cgpa"]].values[3].reshape(2,1)
y=Data[["lpa"]].values[3][0]
Y_hat,A1=L_layer_forward(X,parameters)

A0:  [[12]
 [ 7]]
W1:  [[ 0.86244407  0.86244407  0.86244407]
 [-0.08335381 -0.08335381 -0.08335381]]
b1:  [[0.06903514]
 [0.06903514]
 [0.06903514]]
----------------------------------------
A1:  [[9.83488728]
 [9.83488728]
 [9.83488728]]
****************************************
A1:  [[9.83488728]
 [9.83488728]
 [9.83488728]]
W2:  [[0.38665569]
 [0.38665569]
 [0.38665569]]
b2:  [[0.14555838]]
----------------------------------------
A2:  [[11.55370387]]
****************************************


In [41]:
Y_hat=Y_hat[0][0]

In [42]:
Y_hat

11.553703869549313

In [43]:
update_parameters(parameters,y,Y_hat,A1,X)

In [44]:
parameters

{'W1': array([[ 0.85745057,  0.85745057,  0.85745057],
        [-0.08626668, -0.08626668, -0.08626668]]),
 'b1': array([[0.06861902],
        [0.06861902],
        [0.06861902]]),
 'W2': array([[0.37576446],
        [0.37576446],
        [0.37576446]]),
 'b2': array([[0.14445097]])}

In [53]:
# epochs implementation

parameters = initialize_parameters([2,3,1])
epochs = 10

for i in range(epochs):

  Loss = []

  for j in range(Data.shape[0]):

    X = Data[['iq', 'cgpa']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = Data[['lpa']].values[j][0]

    # Parameter initialization
    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

A0:  [[8]
 [8]]
W1:  [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]
b1:  [[0.]
 [0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.48]]
****************************************
A0:  [[6]
 [9]]
W1:  [[0.10435714 0.10435714 0.10435714]
 [0.10435714 0.10435714 0.10435714]]
b1:  [[0.00054464]
 [0.00054464]
 [0.00054464]]
----------------------------------------
A1:  [[1.56590175]
 [1.56590175]
 [1.56590175]]
****************************************
A1:  [[1.56590175]
 [1.56590175]
 [1.56590175]]
W2:  [[0.108064]
 [0.108064]
 [0.108064]]
b2:  [[0.00504]]
----------------------------------------
A2:  [[0.51269282]]
****************************************
A0:  [[7]
 [5]]
W1:  [[0.11093288 0.11093288 0.11093288]
 [0.11422075 0.11422075 0.11422075]]
b1:  [[0.0016406]
 [0.0016406]
 [0.0016406]]
---------------------------------

{'W1': array([[0.46307506, 0.46307506, 0.46307506],
        [0.26226693, 0.26226693, 0.26226693]]),
 'b1': array([[0.03431351],
        [0.03431351],
        [0.03431351]]),
 'W2': array([[0.43869264],
        [0.43869264],
        [0.43869264]]),
 'b2': array([[0.12424578]])}